### ISSUE TITLE
'@progress/kendo-angular-tasks' is not in the npm registry.

### ISSUE THREAD

**Issue by jimmyjamieson** [telerik/kendo-angular-component-base#10]
I guess something is missing

**Comment by KirilNN** [comment]
Hi @jimmyjamieson,

You are right that the `@progress/kendo-angular-tasks` package is not publicly available which breaks this package. However our intention was to have the starter package publicly available as it is tightly couples with our development process and was not meant for public use. With that said - we will make this repository private in the next few days in order to stop any confusion that it might have. 

If you are looking for a starter seed - this package is based on the https://github.com/AngularClass/angular2-webpack-starter - it might be useful.
