### ISSUE TITLE
What is this repo supposed to do?

### ISSUE THREAD

**Issue by chriscurnow** [telerik/kendo-angular-component-base#3]
I am quite puzzled as to why you would publish this repo – there is really nothing in it.

Am I missing something?

Best regards
Chris

**Comment by tsvetomir** [comment]
Hi @chriscurnow,

Our intention was not to have the starter package publicly available as it is tightly coupled with our development process and was not meant for public use. With that said - we will make this repository private in the next few days in order to stop any confusion that might arise.

If you are looking for a starter seed - this package is based on the https://github.com/AngularClass/angular2-webpack-starter - it might be useful.
